repos:
  - repo: https://github.com/qoomon/git-conventional-commits
    rev: v2.7.2
    hooks:
      - id: conventional-commits
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.45.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [pre-commit]
