keys:
  - &admin_vega age18as6fe55fjr4xdasgelxl55ur8fayzrw2cmh4knhkrm6acwjjecshhmppg
  - &server_licher age13qu697x72h0e0scr5sptqtdc9q8wyfx4sdxh2v3tnj4a0kmvlqhqp5avml
creation_rules:
  - path_regex: secrets/secrets.yaml
    key_groups:
    - age:
      - *admin_vega
      - *server_licher
